// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_speQV3FOfo37-oYSuLBqvdZHuLfPLdQ',
    appId: '1:155261144171:web:2886a7db5b98e68be5752e',
    messagingSenderId: '155261144171',
    projectId: 'chatbird-chatting',
    authDomain: 'chatbird-chatting.firebaseapp.com',
    storageBucket: 'chatbird-chatting.appspot.com',
    measurementId: 'G-ZWTSYCQ2DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXnDjMFsbaWuBXUX7xFIWe1dQ8NHa6CkE',
    appId: '1:155261144171:android:54648d1a7f299bd0e5752e',
    messagingSenderId: '155261144171',
    projectId: 'chatbird-chatting',
    storageBucket: 'chatbird-chatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIEqhku1VZwg-ijLa_TYi4EtR9QVTraE',
    appId: '1:155261144171:ios:024b258ec1a0bf6ce5752e',
    messagingSenderId: '155261144171',
    projectId: 'chatbird-chatting',
    storageBucket: 'chatbird-chatting.appspot.com',
    iosBundleId: 'com.example.chatbird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIEqhku1VZwg-ijLa_TYi4EtR9QVTraE',
    appId: '1:155261144171:ios:85b2932efa1bd19de5752e',
    messagingSenderId: '155261144171',
    projectId: 'chatbird-chatting',
    storageBucket: 'chatbird-chatting.appspot.com',
    iosBundleId: 'com.example.chatbird.RunnerTests',
  );
}
